version: '3'
services:
  app:
    tty: true
    image: danlynn/ember-cli:3.1.2
    ports:
      - "${EMBER_SERVE_PORT-8105}:${EMBER_SERVE_PORT-8105}"
      - "${EMBER_LIVER_PORT-8106}:${EMBER_LIVER_PORT-8106}"
      - "${EMBER_TESTS_PORT-8107}:${EMBER_TESTS_PORT-8107}"
    volumes:
      - .:/myapp:cached
      - node_modules:/myapp/node_modules
      - tmp:/myapp/tmp
    restart: on-failure
    entrypoint: "ember server --port ${EMBER_SERVE_PORT-8105} --live-reload-port ${EMBER_LIVER_PORT-8106} --proxy ${EMBER_GRAPH_PROXY-http://host.docker.internal:8100}"
volumes:
  node_modules: {}
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
